touch ./result/code/0.c
sed 's/REPLACE/0/g' origin/code/0.c > ./result/code/0.c
sed 's/REPLACE/1/g' origin/code/1.c > ./result/code/1.c
sed 's/REPLACE/2/g' origin/code/2.c > ./result/code/2.c
sed 's/REPLACE/3/g' origin/code/3.c > ./result/code/3.c
sed 's/REPLACE/4/g' origin/code/4.c > ./result/code/4.c
sed 's/REPLACE/5/g' origin/code/5.c > ./result/code/5.c
sed 's/REPLACE/6/g' origin/code/6.c > ./result/code/6.c
sed 's/REPLACE/7/g' origin/code/7.c > ./result/code/7.c
sed 's/REPLACE/8/g' origin/code/8.c > ./result/code/8.c
sed 's/REPLACE/9/g' origin/code/9.c > ./result/code/9.c
sed 's/REPLACE/10/g' origin/code/10.c > ./result/code/10.c
sed 's/REPLACE/11/g' origin/code/11.c > ./result/code/11.c
sed 's/REPLACE/12/g' origin/code/12.c > ./result/code/12.c
sed 's/REPLACE/13/g' origin/code/13.c > ./result/code/13.c
sed 's/REPLACE/14/g' origin/code/14.c > ./result/code/14.c
sed 's/REPLACE/15/g' origin/code/15.c > ./result/code/15.c
sed 's/REPLACE/16/g' origin/code/16.c > ./result/code/16.c
sed 's/REPLACE/17/g' origin/code/17.c > ./result/code/17.c
sed 's/REPLACE/18/g' origin/code/18.c > ./result/code/18.c
sed 's/REPLACE/19/g' origin/code/19.c > ./result/code/19.c
sed 's/REPLACE/20/g' origin/code/20.c > ./result/code/20.c
